version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    volumes:
      - java_app:/var/lib/mysql
    networks:
      - appbridge
    restart: always
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  mainapp:
    build:
      context: .
    container_name: Expensetracker
    environment: 
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASSOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Test@123
    ports:
      - "8080:8080"
    networks:
      - appbridge
    depends_on:
      - mysql
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s




volumes:
  java_app:

networks:
  appbridge: